#ifndef KRVERSION_HPP
#define KRVERSION_HPP

#define KR_STRINGIFY_HELPER(a) #a
#define KR_STRINGIFY(a) KR_STRINGIFY_HELPER(a)

#define KR_VERSION_MAJOR 1
#define KR_VERSION_MINOR 0
#define KR_VERSION_BUILD 1337
#define KR_VERSION ((KR_VERSION_MAJOR << 8) | KR_VERSION_MINOR)
#define KR_VERSION_NAME "Kruto.js"
#define KR_VERSION_NUMBER \
		KR_STRINGIFY(KR_VERSION_MAJOR) "." \
		KR_STRINGIFY(KR_VERSION_MINOR) "." \
		KR_STRINGIFY(KR_VERSION_BUILD)

#define KR_VERSION_CHROME "Chrome/24.0.1305.3"

#define KR_VERSION_STRING \
		KR_VERSION_NAME "/" \
		KR_VERSION_NUMBER " " \
		KR_VERSION_CHROME

#define KR_UNUSED(x) (void)(x)

#endif
